### ISSUE TITLE
on  wayland require package qt5-qtwayland

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/provami#32] opened 2019-03-17 09:47 UTC
Fedora 28 with wayland

dbadb wipe --dsn=sqlite:tmp.sqlite

provami-qt sqlite://tmp.sqlite
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dump creato)

**Comment by brancomat** [comment] 2019-03-20 15:47
It's strange, I can't reproduce the bug on a F28 with wayland: I have the same warning about `XDG_SESSION_TYPE` but not the `qt.qpa.plugin` (and I don't have `qt5-qtwayland` installed).

_However_, if I tamper with environment variables by setting `export QT_QPA_PLATFORM=wayland` then, yes, provami-qt crashes. Can you post your `QT_` and `XDG_` environment variables?

**Comment by brancomat** [comment] 2019-03-20 16:18
Further informations: on a fresh F28 install `provami-qt` works with these qt5 packages installed:

```
qt5-qtbase-5.11.3-1.fc28.x86_64
qt5-qtbase-common-5.11.3-1.fc28.noarch
qt5-qtbase-gui-5.11.3-1.fc28.x86_64
qt5-qtdeclarative-5.11.3-1.fc28.x86_64
qt5-qtlocation-5.11.3-1.fc28.x86_64
qt5-qtsensors-5.11.3-1.fc28.x86_64
qt5-qtsvg-5.11.3-1.fc28.x86_64
qt5-qtwebchannel-5.11.3-1.fc28.x86_64
qt5-qtwebkit-5.212.0-0.31.alpha2.fc28.x86_64
qt5-qtxmlpatterns-5.11.3-1.fc28.x86_64
qt5-srpm-macros-5.11.3-1.fc28.noarch
```
if any of them is fundamental to the package and it's not installed as a dependency please let me know

Edit:
as a side note: actually installing `qt5-qtwayland` and  setting `QT_QPA_PLATFORM=wayland` creates huge instabilities on provami-qt (flickering map and selections)

**Comment by brancomat** [comment] 2019-04-12 09:25
If I remember correctly speaking with @pat1 the bug was no longer present / reproducible, I'm closing the issue for now.

**Closed as completed by brancomat** 2019-04-12 09:25 UTC
Labels: bug
